M48
; DRILL file {KiCad (7.0.0)} date Sun Mar  5 21:21:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-05T21:21:57+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X4.76Y-3.02
X5.29Y-3.02
X5.82Y-3.02
X6.35Y-3.02
T0
M30
